scheduled-linter:
  only:
    - schedules
  stage: test
  image: ubuntu:16.04
  script:
    - apt-get update
    - apt-get install -y git
    - git checkout develop
    - git pull
    - sh ./var/build-ubuntu.sh
    - cat ./build/firefox/manifest.json
    - addons-linter --help
    - addons-linter ./build/firefox
