scheduled-linter:
  only:
    - schedules
  stage: test
  image: psono-docker.jfrog.io/ubuntu:22.04
  script:
    - sh ./var/prep-build.sh
    - npm run buildfirefox
    - npm install -g addons-linter@1.17.0
    - cat ./build/firefox/manifest.json
    - addons-linter --help
    - addons-linter ./build/firefox
